### ISSUE TITLE
Can't make rats sit?

### ISSUE THREAD

**Issue by SpacebarMars** [Ladysnake/Rats-Mischief#28]
No matter how much I try to look it up, I can't make rats sit. I have a lot of fabric mods installed, mostly origin mods and better end/better nether. I can't make them sit and it's starting to get annoying. I have right clicked on the rats and everything.

**Comment by doctor4t** [comment]
Are they tamed properly? If they are, it might be mods conflicting with Mischief and pets in general

**Comment by freyquency** [comment]
I've been using a 1.16.5 modpack I put together and could make rats sit but now I cannot. I've also noticed that if I right click there's a chance for them to get hearts, and if I am holding something (eg an iron sword) that the item will disappear if I right click the rat

I'm using about 260 mods, some Origin too. I tried disabling some that I installed afterward but the ones I tried didn't seem to affect it. I also checked the log and nothing listed as weird.

**Comment by freyquency** [comment]
Since I could get rats to sit before and then could not I tested the mods that were installed recently. Through a matter of elimination it appears to be [Lato Origins](https://github.com/Latokike/lato-origins) that prevented my rats from sitting down. If I still experience them gobbling up non-food items I'm holding I'll file it as a separate bug report. It may be related to [Lato Origins issue 14](https://github.com/Latokike/lato-origins/issues/14)
